

services:
  ros2_robot_arm:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2_robot_arm:latest
    container_name: ros2_robot_arm
    volumes:
      - ..:/home/rosuser/ros2_ws
      
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    privileged: true
    devices:
      - /dev/dri:/dev/dri
      - /dev/video0:/dev/video0
    tty: true
    command: bash

volumes:
  ros2_ws:
    name: ros2_ws